default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: recipe_app_development
  username: <%= ENV["RECIPE_APP_DATABASE_USERNAME"] %>
  password: cicibu

test:
  <<: *default
  database: recipe_app_test
  username: <%= ENV["RECIPE_APP_DATABASE_USERNAME"] %>
  password: cicibu

production:
  <<: *default
  database: recipe_app_production
  username: <%= ENV["RECIPE_APP_DATABASE_USERNAME"] %>
  password: cicibu