default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch("PSQL_USER") %>
  password: <%= ENV.fetch("PSQL_PASSWORD") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: recipe_app_development

test:
  <<: *default
  database: recipe_app_test

production:
  <<: *default
  database: recipe_app_production
